# Jekyll Configuration for QBEM Standards

title: QBEM Standards
description: Padronizações Oficiais para Desenvolvimento de Serviços
baseurl: "/standards"
url: "https://qbem-repos.github.io"

# Theme
theme: jekyll-theme-minimal

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Plugins (GitHub Pages native)
plugins:
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index

# Settings
relative_links:
  enabled: true

# Exclude
exclude:
  - .github
  - .gitignore
  - LICENSE
  - _site
  - vendor
