openapi: 3.1.0
info:
  title: Users API
  version: "1.0.0"
  description: API para gestão de usuários
servers:
  - url: https://api.qbem.dev/v1
paths:
  /users:
    get:
      summary: Lista usuários
      operationId: listUsers
      tags: [users]
      parameters:
        - name: cursor
          in: query
          schema: { type: string }
          description: Cursor para paginação
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items: { $ref: "#/components/schemas/User" }
                  next_cursor: { type: string, nullable: true }
                  prev_cursor: { type: string, nullable: true }
  /users/{id}:
    get:
      summary: Detalha usuário
      operationId: getUser
      tags: [users]
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: string }
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema: { $ref: "#/components/schemas/User" }
        "404":
          description: Não encontrado
          content:
            application/problem+json:
              schema: { $ref: "#/components/schemas/Error" }
components:
  schemas:
    User:
      type: object
      required: [id, email, created_at]
      properties:
        id: { type: string, example: "u_123" }
        email: { type: string, format: email, example: "ana@example.com" }
        name: { type: string, nullable: true, example: "Ana" }
        created_at:
          { type: string, format: date-time, example: "2025-09-11T12:00:00Z" }
    Error:
      $ref: "../error-model.md"
