name: Docs CI

on:
  push:
    branches: [main]
    paths:
      - "**/*.md"
      - ".github/**"
  pull_request:
    paths:
      - "**/*.md"
      - ".github/**"

permissions:
  contents: read

jobs:
  markdownlint:
    name: Markdown Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run markdownlint-cli2
        uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          globs: |
            **/*.md
          # Caso crie um .markdownlint.jsonc, ele será detectado automaticamente.

  link-check:
    name: Link Checker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lychee link checker
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args: >-
            --verbose
            --no-progress
            --timeout 20
            --max-redirects 5
            --retry 2
            **/*.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload lychee report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lychee-report
          path: lychee/out.md
